services:
  frontend:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.local
      network: host
    volumes:
      - .:/app
      - frontend-node-modules:/app/node_modules
      - dot-nuxt:/app/.nuxt
    ports:
      - 3000:3000
volumes:
  frontend-node-modules:
  dot-nuxt:
