services:
  frontend:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.local
      network: host
    volumes:
      - .:/app
      - node-modules:/app/node_modules
      - dot-pnpm-store:/app/.pnpm-store
      - dot-nuxt:/app/.nuxt
    ports:
      - 3000:3000
volumes:
  node-modules:
  dot-pnpm-store:
  dot-nuxt:
