FROM oven/bun:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
	git \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json ./
COPY bun.lockb ./
COPY . ./

RUN bun install

CMD ["bun", "run", "dev", "-o", "--host", "0.0.0.0"]

