FROM oven/bun:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
	git \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . ./

CMD ["/bin/sh", "-c", "bun install && bun run dev -o --host 0.0.0.0"]
